<?php

return [
    'payment_methods' => [
        'qris' => 'QRIS',
        'bca_va' => 'BCA Virtual Account',
        'bni_va' => 'BNI Virtual Account',
        'mandiri_va' => 'Mandiri Virtual Account',
        'gopay' => 'GoPay',
        'ovo' => 'OVO',
        'dana' => 'DANA',
    ],

    'games' => [
        'mobile-legends' => [
            'slug' => 'mobile-legends',
            'name' => 'Mobile Legends',
            'developer' => 'Moonton',
            'image' => 'images/mobile_legends.jpg',
            'requires_server' => true,
            'player_id_label' => 'User ID',
            'server_id_label' => 'Zone ID',
            'packages' => [
                'ml_86' => ['name' => '86 Diamonds', 'price' => 20000],
                'ml_172' => ['name' => '172 Diamonds', 'price' => 39000],
                'ml_257' => ['name' => '257 Diamonds', 'price' => 58000],
                'ml_514' => ['name' => '514 Diamonds', 'price' => 112000],
            ],
        ],
        'free-fire' => [
            'slug' => 'free-fire',
            'name' => 'Free Fire',
            'developer' => 'Garena',
            'image' => 'images/free_fire.png',
            'requires_server' => false,
            'player_id_label' => 'Player ID',
            'server_id_label' => null,
            'packages' => [
                'ff_70' => ['name' => '70 Diamonds', 'price' => 11000],
                'ff_140' => ['name' => '140 Diamonds', 'price' => 21000],
                'ff_355' => ['name' => '355 Diamonds', 'price' => 51000],
                'ff_720' => ['name' => '720 Diamonds', 'price' => 101000],
            ],
        ],
        'pubg-mobile' => [
            'slug' => 'pubg-mobile',
            'name' => 'PUBG Mobile',
            'developer' => 'Tencent',
            'image' => 'images/pubg_mobile.png',
            'requires_server' => false,
            'player_id_label' => 'Player ID',
            'server_id_label' => null,
            'packages' => [
                'pubg_60' => ['name' => '60 UC', 'price' => 15000],
                'pubg_325' => ['name' => '325 UC', 'price' => 74000],
                'pubg_660' => ['name' => '660 UC', 'price' => 145000],
                'pubg_1800' => ['name' => '1800 UC', 'price' => 380000],
            ],
        ],
        'genshin-impact' => [
            'slug' => 'genshin-impact',
            'name' => 'Genshin Impact',
            'developer' => 'HoYoverse',
            'image' => 'images/genshin_impact.png',
            'requires_server' => true,
            'player_id_label' => 'UID',
            'server_id_label' => 'Server',
            'packages' => [
                'gi_60' => ['name' => '60 Genesis Crystals', 'price' => 16000],
                'gi_300' => ['name' => '300 + 30 Genesis Crystals', 'price' => 79000],
                'gi_980' => ['name' => '980 + 110 Genesis Crystals', 'price' => 239000],
                'gi_1980' => ['name' => '1980 + 260 Genesis Crystals', 'price' => 479000],
            ],
        ],
        'valorant' => [
            'slug' => 'valorant',
            'name' => 'Valorant',
            'developer' => 'Riot Games',
            'image' => 'images/valorant.png',
            'requires_server' => false,
            'player_id_label' => 'Riot ID',
            'server_id_label' => null,
            'packages' => [
                'val_125' => ['name' => '125 VP', 'price' => 15000],
                'val_420' => ['name' => '420 VP', 'price' => 50000],
                'val_700' => ['name' => '700 VP', 'price' => 80000],
                'val_1375' => ['name' => '1375 VP', 'price' => 155000],
            ],
        ],
        'call-of-duty-mobile' => [
            'slug' => 'call-of-duty-mobile',
            'name' => 'Call of Duty: Mobile',
            'developer' => 'Garena',
            'image' => 'images/call_of_duty_mobile.jpg',
            'requires_server' => false,
            'player_id_label' => 'Open ID',
            'server_id_label' => null,
            'packages' => [
                'cod_80' => ['name' => '80 CP', 'price' => 12000],
                'cod_420' => ['name' => '420 CP', 'price' => 59000],
                'cod_880' => ['name' => '880 CP', 'price' => 118000],
                'cod_2400' => ['name' => '2400 CP', 'price' => 304000],
            ],
        ],
        'roblox' => [
            'slug' => 'roblox',
            'name' => 'Roblox',
            'developer' => 'Roblox Corp',
            'image' => 'images/roblox.jpg',
            'requires_server' => false,
            'player_id_label' => 'Username Roblox',
            'server_id_label' => null,
            'packages' => [
                'rbx_80' => ['name' => '80 Robux', 'price' => 16000],
                'rbx_400' => ['name' => '400 Robux', 'price' => 79000],
                'rbx_800' => ['name' => '800 Robux', 'price' => 155000],
                'rbx_1700' => ['name' => '1700 Robux', 'price' => 309000],
            ],
        ],
    ],
];
